version: '3.8' 

services:
  app:
    build: . 
    ports:
      - "3000:3000" 
    environment: 
      MYSQL_HOST: db 
      MYSQL_USER: tumbuhsehat_user 
      MYSQL_PASSWORD: secure_password 
      MYSQL_DATABASE: tumbuhsehat_db 
    depends_on: 
      - db
    volumes:
      - .:/app 
      - /app/node_modules
  db:
    image: mysql:8.0 
    ports:
      - "3306:3306" 
    environment: 
      MYSQL_ROOT_PASSWORD: super_secret_root_password 
      MYSQL_DATABASE: tumbuhsehat_db 
      MYSQL_USER: tumbuhsehat_user 
      MYSQL_PASSWORD: secure_password 
    volumes:
      - db_data:/var/lib/mysql 
volumes:
  db_data: